### ISSUE TITLE
The addResolveFunctionsToSchema function takes named options now

### ISSUE THREAD

**Issue by MichaelBosch** [gramps-graphql/gramps--legacy#118]
Going through the quickstart gives this error:
The addResolveFunctionsToSchema function takes named options now; see IAddResolveFunctionsToSchemaOptions
/gramps/dist/index.js:35
app.use('/graphql', (0, _apolloServerExpress.graphqlExpress)(GraphQLOptions));

**Comment by jacobfike** [comment]
I also see this error, but my code can still run.

@jlengstorf Is this project no longer being worked on?

**Comment by ryanomackey** [comment]
Hey all! Sorry for the very belated response. This project is still being maintained, but it's just me for the most part. However, I am in the process of making it a monorepo in order to make it a _bit_ easier to maintain, so look forward to a bit more active maintainance going forward.

To that end, I'm going to revisit this once I get that up and running.
